service: auth-server

frameworkVersion: ">=3.0.0"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  timeout: 30
  environment:
    CLIENT_ID: ${file(config.json):CLIENT_ID}
    CLIENT_SECRET: ${file(config.json):CLIENT_SECRET}
    CALENDAR_ID: ${file(config.json):CALENDAR_ID}

functions:
  getAuthURL:
    handler: handler.getAuthURL
    events:
      - http:
          path: api/get-api-url
          method: get
  getAccessToken:
    handler: handler.getAccessToken
    events:
      - http:
          path: api/token/{code}
          method: get
  getCalendarEvents:
    handler: handler.getCalendarEvents
    events:
      - http:
          path: api/get-api-url
          method: get
